name: Copy and Deploy - Prod

on:
  workflow_dispatch:

env:
  PROJECT_ID: cdb-epc-tools-prod-f294
  SERVICE_NAME: cdb-epc-tools-sidepanel-prod-cr
  REGION: us-central1
  JFROG_TEST_URL: burnsmcd.jfrog.io/cor-docker-test-centralus/cdb-epc-tools-sidepanel
  JFROG_PROD_URL: burnsmcd.jfrog.io/cor-docker-prod-centralus/cdb-epc-tools-sidepanel
  DEPLOY_IMAGE: us-docker.pkg.dev/cdb-epc-tools-prod-f294/bmcd-jfrog/cor-docker-prod-centralus/cdb-epc-tools-sidepanel

jobs:
  copy-and-deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to JFrog Artifactory
        env:
          JFROG_USERNAME: ${{ secrets.ARTIFACTORY_COR_CICD_USER_NAME }}
          JFROG_PASSWORD: ${{ secrets.ARTIFACTORY_COR_CICD_TOKEN }}
        run: |
          echo "$JFROG_PASSWORD" | docker login burnsmcd.jfrog.io -u $JFROG_USERNAME --password-stdin

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DEPLOYMENT_SERVICE_ACCOUNT_KEY_PROD }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Pull from Test, tag for Prod, push
        run: |
          docker pull ${{ env.JFROG_TEST_URL }}:${{ github.ref_name }}
          docker tag ${{ env.JFROG_TEST_URL }}:${{ github.ref_name }} ${{ env.JFROG_PROD_URL }}:${{ github.ref_name }}
          docker push ${{ env.JFROG_PROD_URL }}:${{ github.ref_name }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update $SERVICE_NAME \
            --region=$REGION \
            --project=$PROJECT_ID \
            --image="${DEPLOY_IMAGE}:${{ github.ref_name }}"
