name: Copy and Deploy - Prod

on:
    workflow_dispatch:

jobs:
    print-github-ref:
        runs-on: arc-runner-set
        steps:
            - name: Print github.ref
              run: echo "github.ref is ${{ github.ref }}"
    call-reusable-workflow:
        uses: burnsmcd/cor-gcp-cicd-workflows/.github/workflows/copy_build_to_prod.yml@genericize
        with:
            artifact_registry_name: bmcd-jfrog
            container_repo_host: us-docker.pkg.dev
            image_name: cdb-epc-tools-sidepanel
            image_tag: ${{ github.ref_name }}
            project_id: cdb-epc-tools-prod-f294
            service_name: cdb-epc-tools-sidepanel-prod-cr

        secrets:
            DEPLOYMENT_SERVICE_ACCOUNT_KEY: ${{ secrets.DEPLOYMENT_SERVICE_ACCOUNT_KEY_PROD }}
            ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_COR_CICD_USER_NAME }}
            ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_COR_CICD_TOKEN }}